image: fedora:rawhide

variables:
  DEPENDENCIES: gcc gtk2-devel meson

build_stable:
  before_script: 
    - dnf update -y --nogpgcheck
    - dnf install -y --nogpgcheck $DEPENDENCIES
  script: 
    - meson . _build --prefix=/usr
    - ninja -C _build
    - ninja -C _build install
