# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  before_script: 
    - apt update && apt -y --no-install-recommends install make autoconf gnome-common libgtk2.0-dev
  script: 
    - ./autogen.sh --disable-gtk3-engine
    - make
    - make install